/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.PedidosBean;
import model.PedidosDAO;

/**
 *
 * @author João Paulo
 */
public class InicioProprietario extends javax.swing.JFrame {

    /**
     * Creates new form InicioAdmin
     */
    private String ultimoHashPedidos = "";

    private String gerarHash(List<PedidosBean> lista) {
        StringBuilder sb = new StringBuilder();
        for (PedidosBean p : lista) {
            sb.append(p.getId())
                    .append(p.getNomeCliente())
                    .append(p.getTipoLanche())
                    .append(p.getQuantidade())
                    .append(p.getFormaPagamento())
                    .append(p.getValorTotal())
                    .append(p.getStatusPedido())
                    .append("|");
        }
        return sb.toString();
    }

    private void carregarPedidos() {
        PedidosDAO dao = new PedidosDAO();
        List<PedidosBean> lista = dao.listarPedidos();

        String novoHash = gerarHash(lista);
        if (novoHash.equals(ultimoHashPedidos)) {
            return;
        }
        ultimoHashPedidos = novoHash;

        DefaultTableModel model = (DefaultTableModel) tablePedidos.getModel();
        model.setRowCount(0);

        for (PedidosBean p : lista) {
            model.addRow(new Object[]{
                p.getId(),
                p.getNomeCliente(),
                p.getTipoLanche(),
                p.getQuantidade(),
                p.getFormaPagamento(),
                p.getValorTotal(),
                p.getStatusPedido()
            });
        }

        if (tablePedidos.getColumnModel().getColumnCount() == 7) {
            TableColumn colId = tablePedidos.getColumnModel().getColumn(0);
            tablePedidos.getColumnModel().removeColumn(colId);
        }
    }

    public InicioProprietario() {
        initComponents();
        carregarPedidos();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Timer timer = new Timer(1000, (e) -> carregarPedidos());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        goToLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JToggleButton();
        attStatusButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InicioProprietario");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        tablePedidos.setBackground(new java.awt.Color(255, 255, 255));
        tablePedidos.setForeground(new java.awt.Color(0, 0, 0));
        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Tipo do lanche", "Quantidade", "Forma de pagamento", "Valor total", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablePedidos);

        goToLogin.setBackground(new java.awt.Color(255, 255, 255));
        goToLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(0, 0, 0));
        goToLogin.setText("Voltar");
        goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Pedidos");

        deleteButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        deleteButton.setText("Excluir pedido");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        attStatusButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        attStatusButton.setText("Atualizar status");
        attStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attStatusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(goToLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(218, 218, 218)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(attStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attStatusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goToLoginActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (tablePedidos.getSelectedRow() != -1) {
            int linhaSelecionada = tablePedidos.getSelectedRow();
            int id = (int) tablePedidos.getModel().getValueAt(linhaSelecionada, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esse pedido?", "Confirmação", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String statusAtual = tablePedidos.getModel().getValueAt(linhaSelecionada, 6).toString();
                if ("Pendente".equals(statusAtual) || "Entregue".equals(statusAtual)) {
                    PedidosDAO dao = new PedidosDAO();
                    dao.deletePedido(id);
                    JOptionPane.showMessageDialog(this, "Pedido excluido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Pedido em andamento nao pode ser excluido!", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um pedido para excluir!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void attStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attStatusButtonActionPerformed
        if (tablePedidos.getSelectedRow() != -1) {

            DefaultTableModel grcPedidos = (DefaultTableModel) tablePedidos.getModel();
            int linhaSelecionada = tablePedidos.getSelectedRow();

            String statusAtual = grcPedidos.getValueAt(linhaSelecionada, 6).toString();
            int idPedido = (int) grcPedidos.getValueAt(linhaSelecionada, 0);

            String proximoStatus = null;
            PedidosDAO dao = new PedidosDAO();

            if ("Pendente".equals(statusAtual)) {
                proximoStatus = "Em andamento";
            } else if ("Em andamento".equals(statusAtual)) {
                proximoStatus = "Entregue";
            } else {
                proximoStatus = "Pendente";
            }

            dao.atualizarStatus(idPedido, proximoStatus);

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um pedido para atualizar!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_attStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioProprietario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioProprietario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton attStatusButton;
    private javax.swing.JToggleButton deleteButton;
    private javax.swing.JButton goToLogin;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablePedidos;
    // End of variables declaration//GEN-END:variables
}
