/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import model.PedidosBean;
import model.PedidosDAO;
import model.SessaoUsuario;

/**
 *
 * @author João Paulo
 */
public class InicioCliente extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private String ultimoHashPedidos = "";

    private String gerarHash(List<PedidosBean> lista) {
        StringBuilder sb = new StringBuilder();
        for (PedidosBean p : lista) {
            sb.append(p.getId())
                    .append(p.getNomeCliente())
                    .append(p.getTipoLanche())
                    .append(p.getQuantidade())
                    .append(p.getFormaPagamento())
                    .append(p.getValorTotal())
                    .append(p.getStatusPedido())
                    .append("|");
        }
        return sb.toString();
    }

    private void carregarPedidos() {
        PedidosDAO dao = new PedidosDAO();
        List<PedidosBean> lista = dao.listarPedidosCliente();

        String novoHash = gerarHash(lista);
        if (novoHash.equals(ultimoHashPedidos)) {
            return;
        }
        ultimoHashPedidos = novoHash;

        DefaultTableModel model = (DefaultTableModel) tablePedidosCliente.getModel();
        model.setRowCount(0);

        for (PedidosBean p : lista) {
            model.addRow(new Object[]{
                p.getId(),
                p.getTipoLanche(),
                p.getQuantidade(),
                p.getFormaPagamento(),
                p.getStatusPedido()
            });
        }

        tablePedidosCliente.getColumnModel().getColumn(0).setMinWidth(0);
        tablePedidosCliente.getColumnModel().getColumn(0).setMaxWidth(0);
        tablePedidosCliente.getColumnModel().getColumn(0).setWidth(0);
    }

    public InicioCliente() {
        initComponents();
        carregarPedidos();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        Timer timer = new Timer(1000, (e) -> carregarPedidos());
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        tipoLanche = new javax.swing.JComboBox<>();
        quantidade = new javax.swing.JTextField();
        efetuarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        formaPagamento = new javax.swing.JComboBox<>();
        goToLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidosCliente = new javax.swing.JTable();
        buttonEditarPedido = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InicioCliente");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        tipoLanche.setBackground(new java.awt.Color(255, 255, 255));
        tipoLanche.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoLanche.setForeground(new java.awt.Color(0, 0, 0));
        tipoLanche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S. de frango no pão sírio", "S. de frango no pão integral", "S. de peru no pão sírio", "S. de peru no pão integral" }));
        tipoLanche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoLancheActionPerformed(evt);
            }
        });

        quantidade.setBackground(new java.awt.Color(255, 255, 255));
        quantidade.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                quantidadeComponentHidden(evt);
            }
        });
        quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeActionPerformed(evt);
            }
        });
        quantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantidadeKeyReleased(evt);
            }
        });

        efetuarPedido.setBackground(new java.awt.Color(255, 255, 255));
        efetuarPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        efetuarPedido.setForeground(new java.awt.Color(0, 0, 0));
        efetuarPedido.setText("Efetuar pedido");
        efetuarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(" Tipo do lanche");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quantidade");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Forma de pagamento");

        formaPagamento.setBackground(new java.awt.Color(255, 255, 255));
        formaPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        formaPagamento.setForeground(new java.awt.Color(0, 0, 0));
        formaPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Dinheiro à vista", "Débito à vista", "Crédito à vista" }));
        formaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formaPagamentoActionPerformed(evt);
            }
        });

        goToLogin.setBackground(new java.awt.Color(255, 255, 255));
        goToLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(0, 0, 0));
        goToLogin.setText("Voltar");
        goToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goToLoginActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Realizar pedido");

        tablePedidosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tipo", "Quantidade", "Forma de pagamento", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablePedidosCliente);

        buttonEditarPedido.setBackground(new java.awt.Color(255, 255, 255));
        buttonEditarPedido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonEditarPedido.setForeground(new java.awt.Color(0, 0, 0));
        buttonEditarPedido.setText("Editar pedido");
        buttonEditarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(efetuarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goToLogin)
                        .addGap(161, 161, 161)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(goToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tipoLanche, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(formaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(efetuarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonEditarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeActionPerformed
    }//GEN-LAST:event_quantidadeActionPerformed

    private void tipoLancheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoLancheActionPerformed
    }//GEN-LAST:event_tipoLancheActionPerformed

    private void quantidadeComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_quantidadeComponentHidden
    }//GEN-LAST:event_quantidadeComponentHidden

    private void efetuarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarPedidoActionPerformed
        String currentTipoLanche = tipoLanche.getSelectedItem().toString();
        String currentQuantidade = quantidade.getText().trim();
        String currentFormaPagamento = formaPagamento.getSelectedItem().toString();

        if (currentQuantidade.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o campo quantidade!");
        } else {
            try {
                int qtd = Integer.parseInt(currentQuantidade);
                double total = 8.50 * qtd;
                String valorTotal = String.format("%.2f", total);
                JOptionPane.showMessageDialog(null, "Valor calculado: " + valorTotal);
                PedidosDAO dao = new PedidosDAO();
                PedidosBean pedidosFeitos = new PedidosBean(
                        SessaoUsuario.usuarioLogado.getId(),
                        currentTipoLanche,
                        qtd,
                        currentFormaPagamento,
                        total,
                        "Pendente"
                );
                dao.efetuarPedido(pedidosFeitos);
                JOptionPane.showMessageDialog(null, "Pedido efetuado com sucesso!");
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Quantidade deve ser um número!");
            }
        }
    }//GEN-LAST:event_efetuarPedidoActionPerformed

    private void formaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formaPagamentoActionPerformed
    }//GEN-LAST:event_formaPagamentoActionPerformed

    private void quantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantidadeKeyReleased
    }//GEN-LAST:event_quantidadeKeyReleased

    private void goToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goToLoginActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goToLoginActionPerformed

    private void buttonEditarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarPedidoActionPerformed
        if (tablePedidosCliente.getSelectedRow() != -1) {
            DefaultTableModel grcPedidos = (DefaultTableModel) tablePedidosCliente.getModel();
            int linhaSelecionada = tablePedidosCliente.getSelectedRow();

            String status = grcPedidos.getValueAt(linhaSelecionada, 4).toString();

            if (!status.equals("Pendente")) {
                JOptionPane.showMessageDialog(this,
                        "Este pedido não pode ser editado pois está com status: " + status,
                        "Edição bloqueada",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            int id = Integer.parseInt(grcPedidos.getValueAt(linhaSelecionada, 0).toString());
            String novoTipo = tipoLanche.getSelectedItem().toString();
            String novaQtdStr = quantidade.getText().trim();
            String novaPagamento = formaPagamento.getSelectedItem().toString();

            if (novaQtdStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o campo quantidade!");
                return;
            }

            try {
                int novaQtd = Integer.parseInt(novaQtdStr);
                PedidosDAO dao = new PedidosDAO();
                dao.atualizarPedido(id, novoTipo, novaQtd, novaPagamento);
                JOptionPane.showMessageDialog(this, "Pedido atualizado com sucesso!");

                grcPedidos.setValueAt(novoTipo, linhaSelecionada, 1);
                grcPedidos.setValueAt(novaQtd, linhaSelecionada, 2);
                grcPedidos.setValueAt(novaPagamento, linhaSelecionada, 3);

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantidade deve ser um número!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um pedido para atualizar!", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_buttonEditarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEditarPedido;
    private javax.swing.JButton efetuarPedido;
    private javax.swing.JComboBox<String> formaPagamento;
    private javax.swing.JButton goToLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTable tablePedidosCliente;
    private javax.swing.JComboBox<String> tipoLanche;
    // End of variables declaration//GEN-END:variables
}
